# Generated by Django 5.2.9 on 2026-04-07 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0007_booking_bus_class_booking_bus_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='seat',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='driver_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='operator',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
