# Generated by Django 5.2.9 on 2026-04-08 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0009_booking_latitude_booking_longitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='discount_rp',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='booking',
            name='service_fee',
            field=models.IntegerField(default=0),
        ),
    ]
