name: swifttrip_frontend
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.11.0
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.10+1
  curved_navigation_bar: ^1.0.6
  google_fonts: ^6.3.2
  dio: ^5.9.2
  flutter_secure_storage: ^9.2.2
  shared_preferences: ^2.3.2
  http: ^1.2.2
  intl: ^0.19.0
  image_picker: ^1.1.2
  image_picker_for_web: ^3.0.7
  google_maps_flutter: ^2.16.0
  flutter_map: ^8.2.2
  latlong2: ^0.9.1
  provider: ^6.1.5+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: "^0.13.1"

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/app_logo.png"
  min_sdk_android: 21

flutter:
  uses-material-design: true
  assets:
    - assets/fonts/
    - assets/icons/
    - assets/icons/navbar/
    - assets/images/
    - assets/images/home/
    - assets/images/searching/

