# Generated by Django 5.2.9 on 2026-03-30 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotions', '0003_alter_promotion_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotion',
            name='discount_value',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='promotion',
            name='min_purchase',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='promotion',
            name='promotion_type',
            field=models.CharField(choices=[('PERCENTAGE', 'Percentage Discount'), ('CASHBACK', 'Flat Cashback')], default='PERCENTAGE', max_length=20),
        ),
    ]
