# Generated by Django 5.2.9 on 2026-03-24 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel_data', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='features',
            field=models.JSONField(default=list),
        ),
    ]
