# Generated by Django 5.2.9 on 2026-03-24 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel_data', '0004_alter_destination_category_delete_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransportRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin_code', models.CharField(max_length=10)),
                ('destination_code', models.CharField(max_length=10)),
                ('departure_time', models.DateTimeField()),
                ('vehicle_type', models.CharField(max_length=50)),
                ('price_rp', models.IntegerField()),
            ],
        ),
    ]
